name: Bug Reports 🪲🐛🐜🪳🐞
description: Create a bug report to help us improve
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        # Please follow these steps first
        > [!IMPORTANT]
        > If zrok is not behaving the way you expect, we'd ask you to ask for help using [our official support forum](https://openziti.discourse.group/) first.
        > If you are certain you're hitting a bug, we'll ask for steps to reproduce below. Bug reports without clear steps to reproduce will be rejected. If you're unsure of the steps to reproduce, have a discussion on [our official support forum](https://openziti.discourse.group/) first.

        ---
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        The version of zrok you are using. You can find this by running `zrok version`
        Is it the [latest](https://github.com/openziti/zrok/releases)? If not, please 
        check/est and see if the bug has already been fixed.
      placeholder: ex. v0.4.39 [9dce9b71]
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Try to describe as accurately as possible how we can reproduce/verify 
        the bug. If there's any additional context that is possibly helpful, add it here
      placeholder: |
        Example steps (replace with your own):
        1. enable a zrok environment
        2. run `zrok share public localhost:1234
        3. use browser to access http://localhost:1234
        4. observe [problem] here
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Tell us what you expected to see instead
      description: A description of what you expect to happen.
      placeholder: I expected to see my website, instead I was shown an "interstitial page"
    validations:
      required: true
    validations:
      required: true
