blank_issues_enabled: false
contact_links:
  - name: Need help? Ask a question on our Discourse forum 💬
    url: https://openziti.discourse.group/
    about: We prefer using Discourse for support. GitHub should be used for feature requests or bug reports only.