name: Feature Request 🚀
description: Submit a proposal for a new feature
title: '[Feature]: '
body:
  - type: markdown
    attributes:
      value: |
        #### Thank you for taking the time to suggest a new feature!
  - type: textarea
    id: description
    attributes:
      label: '🚀 Feature Request'
      description: A clear and concise description of what the feature is.
    validations:
      required: true
    validations:
      required: true
