version: "3.3"
services:
  browzer-keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    restart: always
    user: root

    volumes:
      - /data/docker/letsencrypt:/etc/letsencrypt
      - browzer-keycloak-data:/opt/keycloak/data
      - /data/docker/keycloak/themes/mytheme:/opt/keycloak/themes/mytheme
    
    ports:
      - "8446:8446"
    
    environment:
      - KEYCLOAK_ADMIN=keycloak_admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak!
    
    command:
      - "start"
      - "--https-certificate-file=/etc/letsencrypt/live/clint.demo.openziti.org/fullchain.pem"
      - "--https-certificate-key-file=/etc/letsencrypt/live/clint.demo.openziti.org/privkey.pem"
      - "--hostname=keycloak.clint.demo.openziti.org"
      - "--https-port=8446"

  browzer-bootstrapper:
    image: ghcr.io/openziti/ziti-browzer-bootstrapper:latest
    restart: always

    volumes:
      - /usr/local/ziti/log:/home/node/ziti-http-agent/log
      - /data/docker/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/.browzer/pki:/ziti

    ports:
      - "443:443"

    environment:
      NODE_ENV: production
      ZITI_BROWZER_BOOTSTRAPPER_LOGLEVEL: debug
      ZITI_BROWZER_RUNTIME_LOGLEVEL: debug
      ZITI_CONTROLLER_HOST: ctrl.clint.demo.openziti.org
      ZITI_CONTROLLER_PORT: 8441
      ZITI_BROWZER_BOOTSTRAPPER_HOST: browzer.clint.demo.openziti.org
      ZITI_BROWZER_BOOTSTRAPPER_LISTEN_PORT: 443
      ZITI_BROWZER_BOOTSTRAPPER_CERTIFICATE_PATH: /etc/letsencrypt/live/clint.demo.openziti.org/fullchain.pem
      ZITI_BROWZER_BOOTSTRAPPER_KEY_PATH: /etc/letsencrypt/live/clint.demo.openziti.org/privkey.pem
      ZITI_BROWZER_BOOTSTRAPPER_SCHEME: https
      ZITI_BROWZER_BOOTSTRAPPER_TARGETS: >
          {
            "targetArray": [
            {
                       "vhost": "docker-whale.clint.demo.openziti.org",
                       "service": "docker.whale",
                       "path": "/",
                       "scheme": "http",
                       "idp_issuer_base_url": "https://keycloak.clint.demo.openziti.org:8446/",
                       "idp_client_id": "browzerBootstrapClient",
                       "idp_type": "keycloak",
                       "idp_realm": "zitirealm"
            },
            {
                      "vhost": "brozac.clint.demo.openziti.org",
                      "service": "brozac",
                      "path": "/",
                      "scheme": "http",
                      "idp_issuer_base_url": "https://keycloak.clint.demo.openziti.org:8446/realms/zitirealm",
                      "idp_client_id": "browzerBootstrapClient",
                      "idp_type": "keycloak",
                      "idp_realm": "zitirealm"
            }
            ]
          }

  docker-whale:
    image: crccheck/hello-world
    ports:
      - "2000:8000"
  
  ziti-console:
    image: openziti/zac
    user: root
    working_dir: /usr/src/app
    environment:
      - ZITI_CTRL_EDGE_ADVERTISED_ADDRESS=ec2-3-142-245-63.us-east-2.compute.amazonaws.com
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=8441
      - ZITI_CTRL_NAME=ip-172-31-11-231
      - PORTTLS=8443
      - ALLOW_HTTP=true
    ports:
      - 0.0.0.0:1408:1408
      - 0.0.0.0:7443:8443
    volumes:
      - browzer-ziti-fs:/persistent
      - /etc/letsencrypt/live/clint.demo.openziti.org/fullchain.pem:/usr/src/app/server.chain.pem
      - /etc/letsencrypt/live/clint.demo.openziti.org/privkey.pem:/usr/src/app/server.key
  
  pkce-tester:
    image:  dovholuknf/pkce-debugging
    ports:
      - 8450:8080
    environment:
      - TLS_CERT=/etc/letsencrypt/live/clint.demo.openziti.org/fullchain.pem
      - TLS_KEY=/etc/letsencrypt/live/clint.demo.openziti.org/privkey.pem
      - AUTH_URL=https://keycloak.clint.demo.openziti.org:8446/realms/zitirealm/protocol/openid-connect/auth
      - TOKEN_URL=https://keycloak.clint.demo.openziti.org:8446/realms/zitirealm/protocol/openid-connect/token
      - CLIENT_ID=browzerBootstrapClient
    volumes:
      - /data/docker/letsencrypt:/etc/letsencrypt

volumes:
  browzer-keycloak-data:
  browzer-ziti-fs:
